### PR TITLE
[Pod] Count deprecated_in_favor_of pods as deprecated as well

### LINKED ISSUE #91: Pods should be considered deprecated if there is just `deprecated_in_favor_of`
Right now it looks like a pod like [mailcore2](https://github.com/CocoaPods/Specs/blob/master/Specs/mailcore2/0.4.7/mailcore2.podspec.json) gets its deprecation ignored due to `deprecated` not being set to true, which makes sense, but isn't really a reflection on how people are actually using `deprecated_in_favor_of`.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #91 ?

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this was what I was gonna go with too, but I couldn't even get a `bundle install` working, let alone being able to test it :dancers:

**Comment by floere** [comment]
@orta Maybe next time open an issue if you have trouble with bundle install?

**Comment by floere** [comment]
@segiddins Adding a test in pod_spec.rb would be great! :) (Or do you also have trouble installing?)

**Comment by segiddins** [comment]
The dump version used for the specs seems to be unavailable so I have 9 failing specs to begin with

**Comment by floere** [comment]
You are right. It's gone. I haven't got a great idea yet for replacing the dump as a realistic search engine test bed.

**Comment by floere** [comment]
Thanks @segiddins! :rocket: :smiley:

**Pull request merged**
